---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-system-secret
  namespace: order-system
spec:
  encryptedData:
    MYSQL_PASSWORD: AgB4N3+0jrAl4HdrI6ALmJo1ScX7al+aEwCvBrb6xWHMcpvW6pZWONcpRdUccDObPA+8kJcuUzXuRJ34ZIBamPZ1lslyj2ANEGisJRtWOxa7+CVzRoSjzmpw8HK/jmB7ZDIJ8BEsMcs8DKLTgBkDyv1WNZVRfFymha7bKJb2Rfj+qAKbpBsHnU2nJgFt3qJv52b9p5qP7o4aFhz1TF8JzyQoGeVj2gojErL0+cFf9OTYkylJ6fnMLUwfC8bgtKGgLE++1XWJ5jW6ffn5fg7czrvgQ5vv5CynsBb0AY+8RwONxgzwAbvFNLAmEvb5ktaH5+65euR1vrAHIrrnDv3x0ugBljowN22QU1V02vi//6RTgTzsQEPdKmKL3wrnzRoTGX+1k1K9LE07ZXVnWH1BfzFHHAhIjc2rq2p+LV+4s+2T1JK/kNVkKlxZCVmE1kd24By5F/DgPw3VGW6bGeyL95hLEjX1ZNngHyik5uBMHaGl1D38pL4lO7tyKCHApXrLjfwgNUz14mC89tLtrZhToopZFEQ3L5OkQ0Ji9TwRa5ywChki4pErdWcowszqOFwPTM7fQIhR/Zv214m+QoZffTRctxQaT2CR33M8Vcw222AJEY+1g9jtN8kpKzVF0I5HyFI/erKYikUxRW+KyxBodmxWhgrRcjXypkM4rYoU7AZf4MhlqKqgCwGAtl7Xjg9KvHseTMX8xIarMBzoGQ==
    REDIS_PASSWORD: AgBvyZaYmd7FUbhY3hruCuyejpIb8ehFs4j5HJMzmk94D+6THSu+lGqC+EebmjJRoqq1pRLiyVIMCa7Vv7cXAMi6hYzLS6dJE5K0PKf81HVGVN0/mhvsVItKdTVzQgQ1boWVRh6WBeVAoMrX7dGgXQc3nHXPVqobIbjPW5Cjbqu7darAc3lmvJXQe6HrBDJWu7L4A0vbiP8nqilzFCE3GuWryA0mz15bxfE9i0ymWn2buxrzontjIzm8dW3TyUAqAfkumOwSOyv41HHxb0RbDtFtiS+auWy07h5e0YwLY21DLQRPfC9gP+X9jzsj049bcr+dWc1NKYR2gAO0Bd2oXcbH5AkcqqcmJHcu4RDOjXs9fZg5SIHdfICjXBfi5x0k8H4i2lKe1273Xc3Zo4cp7UFagmzsIqh48eIhL/OfinhRuikxaBQmUliGE8AEJjFkPkY/uUY48Yp5LhZvAHMM3ILN5IZ06rbEnnVT2aAaSlqWcul1J9l9bq7ZpmoAnX8uKSbkpHnyeMKPE6b4WImWPfEDjTJ7oKNK4T7uTWVTGL5RzcHgrqKB+4uQEg2vXTHmzdZqJCcP1aJTr/iUiviyit1aRBIc4mzq/Zm8JdTg8/JLe8A+6QVifCe1BCTN8ShMVQqHoVDj/7hBlTb/yNxDLLdeax2Rr+jpEE2NHL+mZfg2U20kjGuC3BnmmitVWhx8t1k=
  template:
    metadata:
      creationTimestamp: null
      name: order-system-secret
      namespace: order-system
    type: Opaque
