apiVersion: v1
kind: Secret
metadata:
  name: order-system-secret
  namespace: order-system
type: Opaque
stringData:
  MYSQL_PASSWORD: "Horror4199."
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
  namespace: order-system
type: Opaque
data:
  # Base64 закодированные ключи — заполнить при деплое
  # kubectl create secret generic jwt-keys --from-file=private.pem=secrets/jwt/private.pem --from-file=public.pem=secrets/jwt/public.pem -n order-system
  public.pem: ""
  private.pem: ""
