apiVersion: v1
kind: Secret
metadata:
  name: order-system-secret
  namespace: order-system
type: Opaque
stringData:
  MYSQL_PASSWORD: "Horror4199."
  REDIS_PASSWORD: ""
# jwt-keys создаётся отдельно в CD workflow из локальных файлов
